# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Production CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  tags : 
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
 FLUTTER_VERSION: "3.10.0"
 TAG_NAME: "1.0.0"

jobs:
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    # we need java to build android apks
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # this flutter action does the heavy lifting for us
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'  
    # get packages as you used to in your computer
    - run: flutter pub get
    - run: dart analyze
    # Now build apk
    - run: flutter build apk --split-per-abi
    # now relase the just created build
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        # token: ${{ secrets.MY_REPO_SECRET }}
