name: Upload APK as Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build APK
        run: flutter build apk

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #   with:
      #     tag_name: v${{ github.run_number }}
      #     release_name: Release v${{ github.run_number }}
      #     draft: false
      #     prerelease: false

      # - name: Upload APK
      #   id: upload_asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: build/app/outputs/flutter-apk/app-release.apk
      #     asset_name: MyApp-v${{ github.run_number }}.apk
      #     asset_content_type: application/vnd.android.package-archive


      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}